### ISSUE TITLE
[Feat] Font and color configuration

### ISSUE THREAD

**Issue by marekkaczkowski** [krnik/vscode-jumpy#3]
Hey @krnik it would be awesome to get style settings working:

```
  "jumpy.fontFamily": "Operator Mono Lig, monospace",
  "jumpy.fontSize": "9",
  "jumpy.darkThemeBackground": "#93b7cc",
  "jumpy.darkThemeForeground": "#08df91",
  "jumpy.lightThemeBackground": "#93b7cc",
  "jumpy.lightThemeForeground": "#08df91",
```

Will take a look into that, expect PR soon ;)

**Comment by ghost** [comment]
Great, if you would like to get some help just send me a message/notify me. 
I will have some time this week starting tomorrow to help out ;)

**Comment by wenfangdu** [comment]
@marekkaczkowski Any news?

**Comment by ghost** [comment]
This feature can be implemented by taking advantage of [`activeColorTheme`](https://code.visualstudio.com/api/references/vscode-api#window) window property which can be used to retrieve the relevant setting value.

See [`buildDecorationType`](https://github.com/krnik/vscode-jumpy/blob/de1d75877d2a93cb31315ff3109642585a90fadb/src/jumpy/settings.ts#L117-L119)

```ts
  const { kind } = window.activeColorTheme;
  const colorConfigKey = kind === ColorThemeKind.Light
    ? DisplaySetting.ColorLight
    : kind === ColorThemeKind.Dark
    ? DisplaySetting.ColorDark
    : DisplaySetting.ColorHighContrast;
   const color = jumpyConfig.get<string>(colorConfigKey) || DEFAULT_COLOR;
```
