### ISSUE TITLE
Decorators does not appear in view if current carret position is out of it.

### ISSUE THREAD

**Issue by JhosdryG** [krnik/vscode-jumpy#5]
decorators are only printed in the current view and not in the whole document, this makes sense and it's perfect, but when current carret or mouse position is out of the view decorators are no printed, this is annoying because if you are in a line then you scroll down/up and then you want to jump to a word you use the command but it is useless because decorator are no printed, then if you scroll back to the current position decorator will not appear until you click the editor again.

If you want to jump to a word out of the view you would have to take the carret or mouse to the view of that word that means an extra step.

it would be fine if decorators were printed in the current view wherever the carret is positioned.

**Comment by ghost** [comment]
Noted, I'll play with it to see if it works smoothly.
So rather than always decorating area near the cursor, the scroll event will trigger the decoration for newly visible area of the document.

**Comment by ghost** [comment]
Update: I added appropriare logic so that decorators are refreshed on scroll. I will push the changes to the master once I will implement proper debounce function so that extension does not re-render the decorators multiple times in a short time span.

**Comment by JhosdryG** [comment]
Could make decorators re-render only when scroll event finish. One thing, usually you will first scroll to the target word and then after that you activate the extesion to print decorators, this for better readability of words, so will the extension print decorators in new view when active even when scroll view when it was not active?

**Comment by ghost** [comment]
So, basically it should exit the jump mode when the scroll event happens?
Currently it has a hardcoded `80ms` timeout on the redraw so the scroll event looks like bleow:
![jumpy-80](https://user-images.githubusercontent.com/26797767/109531819-abcf6900-7ab8-11eb-838d-6cf1505cef03.gif)

There are two ways I can think of on how to handle it:
1) Turn off jump mode when scroll event occurs.
2) Make the debounce a setting. But it may not be always convenient - sometimes it takes longer to find what we are looking for.

I think the first approach may be better. But maybe it should turn off once the cursor is no longer visible rather than on first scroll event. Let me know what you think - I may not be the best UX designer ^^

**Comment by JhosdryG** [comment]
No, it should not exit when the scroll envent happens, actually the current behavior you show is great, but note that decorators are re-render when you scroll and the mode is active and this is perfectly ok good job! but what if for example i have the mouse or carret on first word, and then **without** active the jumpy mode i scroll  to the word i want and then finally active the jumpy mode. Will this render decorators in new view? 

The idea is to show decorators even when the cursor is no longer visible, as you show above. but first a will look for the word i want, for this i will not active jumpy mode because decorators will distract and then when i find the word i want is when i will active jumpy mode and decorators should be printed in new view even if cursor is out  of it. then as you show above **if** i scroll again with jumpy mode active decorators will be re-render in new view.

do not if i express well jeje, but hope you get the idea.

**Comment by ghost** [comment]
> but what if for example i have the mouse or carret on first word, and then **without** active the jumpy mode i scroll to the word i want and then finally active the jumpy mode. Will this render decorators in new view?

Yes, currently, if the cursor is not visible on the screen the decorators will be rendered anyway even if the extension is not active. So they are no longer attached to the position of the cursor.

**Comment by JhosdryG** [comment]
That's great! Thanks! Can not wait to try it out, when will it be avalaible in vsc marketplace?

**Comment by ghost** [comment]
That will be.. never actually, sorry. I lost my publisher credentials so I would have to create new published and then create another extension.

You can always build this extension and install it manually:
```sh
git clone https://github.com/krnik/vscode-jumpy.git
cd vscode-jumpy
npm i
npx vsce package
```

This will generate `.vsix` file which needs to be installed from VSCode by running `Extensions: Install from VSIX` command.

**Comment by JhosdryG** [comment]
I have already tried it out, works perfectly, thank you so much man, now it will be easier and faster to jump to a word even if is far away of the cursor. 

I'm sorry to read that about your credentials, but you should paste that piece of code in the home section of the repository so new users can install and use the extension with the new aproach.

You deserve a beer, will close the issue.

**Comment by wenfangdu** [comment]
@JhosdryG This extension is deprecated, please use [Jump](https://marketplace.visualstudio.com/items?itemName=wenfangdu.jump) instead.
