### ISSUE TITLE
Duplicate decorations being rendered

### ISSUE THREAD

**Issue by wenfangdu** [krnik/vscode-jumpy#6]
Custom setting:

```json
{
  "jumpy.primaryCharset": "abcdefghigklmnopqrstuvwxyz"
}
```

Command: `extension.jumpy-enter-end-of-word`

Screenshot:

![image](https://user-images.githubusercontent.com/28700378/120248373-89144280-c2a9-11eb-9609-2fd253076dcb.png)

[sample.txt](https://github.com/krnik/vscode-jumpy/files/6572499/sample.txt)

**Comment by ghost** [comment]
Mentioned above commit fixes this issue.

**Comment by wenfangdu** [comment]
@krnik Thanks for the quick fix!

**Comment by wenfangdu** [comment]
Seems like this hasn't been fixed completely.

When using setting:

```json
{
  "jumpy.primaryCharset": "1234567890"
}
```

Command: `extension.jumpy-enter-end-of-word`

![image](https://user-images.githubusercontent.com/28700378/124144303-6cdd0e80-dabe-11eb-861f-84f43ef93a42.png)

[sample.txt](https://github.com/krnik/vscode-jumpy/files/6749035/sample.txt)

**Comment by ghost** [comment]
Is it reproducible 100% of the times?
I just added this code in this place https://github.com/krnik/vscode-jumpy/blob/9c8c5e007f0defe03bd470669f820a13743f2606/src/jumpy/mod.ts#L237
```ts
const els = this.settings.codes.length;
const size = new Set(this.settings.codes).size;
console.log({ els, size });
```

And it is logging out the same values. Could you confirm whether those values are different for you when this issue occurs?

By the way, to see the output log run the extension in debug mode and it will appear in the `Debug Console`.

**Comment by wenfangdu** [comment]
Yes, 100% reproducible with `"jumpy.primaryCharset": "1234567890"`:

![image](https://user-images.githubusercontent.com/28700378/124195723-9a957800-dafd-11eb-856a-18cfdd7b61ed.png)

The values being logged are `{els: 1036, size: 1036}` when this issue occurs.

**Comment by ghost** [comment]
Thanks, I'll try to debug it from here. It seems it's either an issue with `showDecorations` method or in `Settings` instance when building decorations.

**Comment by wenfangdu** [comment]
@krnik It's really weird, I checked the decorations being produced everywhere, the length is always 1036, even without [this commit](https://github.com/krnik/vscode-jumpy/commit/6a95264b0f73cc1a835488e572999c9a24299874). 

https://github.com/krnik/vscode-jumpy/blob/b05270eb96e9a8bfbfabf22fc0f85cec76c3718e/src/jumpy/settings.ts#L198

`console.log(value)` here still logs 1036 rows of data.

Tried with/without editor wrap, `useIcons: true/false`, the output is always correct, but rendering is wrong.

**Comment by wenfangdu** [comment]
Interestingly, if I swap the `primaryChars` and `secondaryChars` here:

https://github.com/krnik/vscode-jumpy/blob/b05270eb96e9a8bfbfabf22fc0f85cec76c3718e/src/jumpy/char_code.ts#L62

The problem is gone.

---

No, this happened:

![image](https://user-images.githubusercontent.com/28700378/125158630-daff9080-e1a4-11eb-9e70-d2f34a0d3faa.png)

**Comment by ghost** [comment]
How do you detect the duplicates? 😅

**Comment by wenfangdu** [comment]
@krnik Just by reading 🤦‍♂️.

**Comment by ghost** [comment]
Right now the only idea I have is to add `xml:lang` attribute to rendered svg icons.

```diff
diff --git a/src/jumpy/settings.ts b/src/jumpy/settings.ts
index a3c544a..37b9513 100644
--- a/src/jumpy/settings.ts
+++ b/src/jumpy/settings.ts
@@ -224,8 +224,8 @@ export class Settings implements ExtensionComponent {
         const halfOfPad = pad >> 1;
 
         return [
-            `image/svg+xml;utf8,<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${width} ${height}" height="${height}" width="${width}"><rect width="${width}" height="${height}" rx="2" ry="2" fill="${backgroundColor}"></rect><text font-family="${fontFamily}" font-size="${fontSize}px" textLength="${width -
-                pad}" fill="${color}" x="${halfOfPad}" y="${fontSize * 0.8}">`,
+            `image/svg+xml;utf8,<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${width} ${height}" height="${height}" width="${width}"><rect width="${width}" height="${height}" rx="2" ry="2" fill="${backgroundColor}"></rect><text xml:lang="en" font-family="${fontFamily}" font-size="${fontSize}px" textLength="${width -
+            pad}" fill="${color}" x="${halfOfPad}" y="${fontSize * 0.8}">`,
             `</text></svg>`,
         ];
     }
```

**Comment by wenfangdu** [comment]
@krnik I'm curious, why would be that be useful?

**Comment by ghost** [comment]
It's just a guess (maybe rendering of the svg has something to do with it), I'm basically out of ideas at the moment.
Other than that the only thing to do is to read the implementation of `editor.setDecorations` method. Maybe that's the problem.
