### ISSUE TITLE
Is it safe to remove `_forceInvocation = true`? 

### ISSUE THREAD

**Issue by wenfangdu** [krnik/vscode-jumpy#7]
Looks like it's unused in the function:

https://github.com/krnik/vscode-jumpy/blob/9c8c5e007f0defe03bd470669f820a13743f2606/src/jumpy/mod.ts#L311

But it's been passed value here:

https://github.com/krnik/vscode-jumpy/blob/9c8c5e007f0defe03bd470669f820a13743f2606/src/jumpy/mod.ts#L199

Please forgive my ignorance, I'm not very familiar with the decorator syntax.

**Comment by ghost** [comment]
Well, it depends. This parameter is used here (it was included in the `showDecoration` method to calm down the TypeScript :P): https://github.com/krnik/vscode-jumpy/blob/9c8c5e007f0defe03bd470669f820a13743f2606/src/jumpy/mod.ts#L84

`withDelay` decorator on a `showDecorations` method is equivalent to:
```
  showDecorations = debounce(<function definition>, 300)`
```

Basically, if you invoke `this.showDecorations(false)` it will debounce the function - it will execute at least `300ms` after the last invocation.
It is done this way to prevent frequent decoration re-rendering when user scrolls the active editor (scroll event fires quite frequently).

**Comment by ghost** [comment]
You can just replace `this.showDecorations(false)` invocation in here:
https://github.com/krnik/vscode-jumpy/blob/9c8c5e007f0defe03bd470669f820a13743f2606/src/jumpy/mod.ts#L194-L200

By creating a timeout on a class and invoking it like this:
```js
    if (this.timeout) clearTimeout(this.timeout);
    this.timeout = setTimeout(() => this.showDecorations(), 300);
```

Effectively, this will allow you to remove `withDelay` decorator completely and the `_forceInvocation` parameter :)

**Comment by wenfangdu** [comment]
@krnik Thanks for the explanation! I guess these `^_argument`s are safe to remove?
https://github.com/krnik/vscode-jumpy/blob/9c8c5e007f0defe03bd470669f820a13743f2606/src/extension.ts#L6
https://github.com/krnik/vscode-jumpy/blob/9c8c5e007f0defe03bd470669f820a13743f2606/src/jumpy/mod.ts#L194
https://github.com/krnik/vscode-jumpy/blob/9c8c5e007f0defe03bd470669f820a13743f2606/src/jumpy/mod.ts#L202

**Comment by ghost** [comment]
Yes, they were added there just so it would be a bit easier to figure out what kind of events those functions should handle.
