### ISSUE TITLE
[FR] Dynamic length decoration

### ISSUE THREAD

**Issue by wenfangdu** [krnik/vscode-jumpy#8]
Suppose we have set `"jumpy.primaryCharset": "abcdefghijklmnopqrstuvwxyz"`, the decoration length is always two, starting from `aa`, `ab`, `ac` etc. which is a bit wasteful because the decoration could start from `a`, `b`, `c` etc. and works equally fine, besides, there're some extra benefits, such as saving typings and reducing the chance of typos which could cause re-jumps.

There're also cases where the decorations aren't enough to cover all texts on screen, such as in:

![image](https://user-images.githubusercontent.com/28700378/124265051-cf3e1980-db67-11eb-9878-d752823236d6.png)

To solve these issues, I propose dynamic length decoration, starting from one, the max length should be configurable. If we set `3` for the `max`, the produced decorations should be `a` ... `z`, `aa` ... `zz`, `aaa` ... `zzz`.

Could you please consider this feature request?

**Comment by ghost** [comment]
So, basically it should work somehow similar to https://github.com/easymotion/vim-easymotion
I'll figure out how feasible is it to implement ;]

**Comment by wenfangdu** [comment]
@krnik I just watched the demo of Vim Eazymotion, the interaction looks very different from Jumpy. Just to clarify the request, I put the updated desired behavior below:

> To solve these issues, I propose dynamic length decoration, starting from one, the max length should be configurable. If we set `3` for the `max`, the produced decorations should be `a` ... `z`, `aa` ... `zz`, `aaa` ... `zzz`.

**Comment by ghost** [comment]
Well, if this extension were to always display for example decorations with 3 characters in it, then with current setup it would need to create almost 50k (37 ^ 3) codes and 50k decorations for the codes in advance.
I think this should be optimised to have more "create charset on demand" approach.

Just to clarify:
>the produced decorations should be a ... z, aa ... zz, aaa ... zzz.

So it would display both `a` and `aa` at the same time?

**Comment by wenfangdu** [comment]
@krnik

> Well, if this extension were to always display for example decorations with 3 characters in it, then with the current setup it would need to create almost 50k (37 ^ 3) codes and 50k decorations for the codes in advance.
> I think this should be optimized to have a more "create charset on-demand" approach.

Yes, I agree. Probably just create so many that could cover the visible range?

> So it would display both a and aa at the same time?

Yes, I just found out [a PR in the original vscode-jumpy repo](https://github.com/wmaurer/vscode-jumpy/pull/35/commits/43d5c9cac23f9c78744179889ae12a366f00dc12) that seems to do this:

Screenshot:

![image](https://user-images.githubusercontent.com/28700378/124335370-a3a14a80-dbcc-11eb-8950-efd93e26ecf8.png)

**Comment by wenfangdu** [comment]
> Just to clarify:
>
> > the produced decorations should be a ... z, aa ... zz, aaa ... zzz.
>
> So it would display both a and aa at the same time?

@krnik Ah, thanks for pointing it out. I just realized that would be impossible.

To optimize, for example, `"jumpy.primaryCharset": "acdefijklmnopqrsvwxz"` and 100 decorations are needed to cover the visible range, we can have the following combination:

```
i...z - 15
a<x> - 20
c<x> - 20
d<x> - 20
e<x> - 20
f<x> - 5
```

**Comment by ghost** [comment]
Another thing that should be improved is the decoration range. The sample file you submitted pictures it perfectly that decoration is done per "line" instead of using cursor (selection) position.
That's why in this sample file decorations are always displayed at the start of the file even if you scroll down. Simply there are not enough decorations to cover the whole line.

So for the current line decorations shouldn't start from the first character but from the cursor position.

**Comment by wenfangdu** [comment]
Closing in favor of https://github.com/wenfangdu/vscode-jump/issues/2.
